<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Paypal\Block\PayLater\Banner;
use Magento\Checkout\Block\Cart;

/** @var Escaper $escaper */
/** @var Banner $block */
/** @var Cart $cartBlock */

$widgetData = json_decode($block->getJsLayout(), true);
$widgetConfigJson = json_encode($widgetData['components']['payLater']['config']);

$uniqueId = '_' . uniqid();
?>

<?php $cartBlock = $block->getLayout()->getBlock('checkout.cart'); ?>
<?php if ($block->getData('placement') !== 'cart' || is_object($cartBlock) && $cartBlock->getItemsCount()): ?>
    <div x-data="paypalPaylater<?= $escaper->escapeHtmlAttr($uniqueId) ?>()" 
         x-ref="ppMessage"
         @private-content-loaded.window="getSectionData($event.detail.data)"
         class="px-6 md:px-0 my-3 min-h-[20px] order-last"
         data-pp-message></div>
    <script>
        function paypalPaylater<?= $escaper->escapeHtmlAttr($uniqueId) ?>() {
            return {
                
                /**
                 * Configuration object derived from server-side JSON.
                 * @type {Object}
                 */
                config: <?= /** @noEscape */ $widgetConfigJson ?>.config || {},
                
                /**
                 * Shopping cart section data.
                 * @type {Object|boolean}
                 */
                cartSection: false,
                    
                /**
                 * Handles the event when dynamic content related to the cart is loaded.
                 * Updates the cartSection data based on the provided sectionData.
                 * 
                 * @param {Object} sectionData Data about the cart section.
                 */
                getSectionData(sectionData) {
                    if (sectionData.cart) {
                        this.cartSection = sectionData.cart;
                    }
                },
                    
                /**
                 * Initializes the PayPal SDK by dynamically injecting the PayPal script into the page.
                 * Resolves with the PayPal object once the SDK is loaded, or rejects the promise on error.
                 * 
                 * @returns {Promise<Object>} A promise that resolves with the PayPal object.
                 */
                initializePayLater() {
                    return new Promise((resolve, reject) => {
                        const scriptId = 'paypal-script';
                        const config = this.config;

                        let paypalScript = document.getElementById(scriptId);
                        if (paypalScript) {
                            return resolve(window.paypal);
                        }

                        const script = document.createElement('script');
                        script.src = config.sdkUrl;
                        script.id = scriptId;
                        script.setAttribute('data-partner-attribution-id', config.dataAttributes['data-partner-attribution-id']);

                        script.addEventListener('load', function() {
                            resolve(window.paypal);
                        }, false);

                        script.addEventListener('error', function() {
                            reject(new Error('PayPal SDK could not be loaded'));
                        }, false);

                        document.body.appendChild(script);
                    });
                },
                    
                /**
                 * Initializes and renders the PayPal buttons and messages based on the current cart section.
                 * Utilizes the PayPal SDK loaded by initializePayLater.
                 */
                initializeButtons() {
                    this.initializePayLater().then(() => {
                        
                        const paypal = window.paypal;
                        const attributes = this.config.attributes;
                        const cartSection = this.cartSection;
                        
                        paypal.Messages({
                            amount: cartSection.subtotalAmount,
                            placement: attributes['data-pp-placement'] || 'product',
                            style: {
                                'layout': attributes['data-pp-style-layout'] || 'text',
                                'logo': {
                                    'type': attributes['data-pp-style-logo-type'] || 'primary',
                                    'position': attributes['data-pp-style-logo-position'] || 'left',
                                },
                                'text': {
                                    'color': attributes['data-pp-style-text-color'] || 'black',
                                    'size': attributes['data-pp-style-text-size'] || '12',
                                },
                                'color': attributes['data-pp-style-color'] || 'blue', 
                                'ratio': attributes['data-pp-style-ratio'] || '1x1',
                            },
                        }).render(this.$refs.ppMessage);
                    }).catch(error => {
                        console.error(error.message);
                    });
                },
                    
                /**
                 * Initialization method that sets up event listeners for the module.
                 */
                init() {
                    window.addEventListener('init-external-scripts', () => {
                        this.initializeButtons()
                    }, { once: true, passive: true });
                }
            };
        }
    </script>
<?php endif; ?>
