<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Paypal\Block\Express\InContext\SmartButton;

/** @var SmartButton $block */
/** @var Escaper $escaper */

$widgetData = json_decode($block->getJsInitParams(), true);
$widgetJson = json_encode($widgetData['Magento_Paypal/js/in-context/product-express-checkout']);

$uniqueId   = '_' . uniqid();
?>

<div x-data="initPayPalInContext<?= $escaper->escapeHtmlAttr($uniqueId) ?>()"
     @private-content-loaded.window="getData($event.detail.data)"
     class="min-h-[42px]">
    <div x-ref="paypalInContextProduct"
         class="paypal checkout paypal-logo <?= $escaper->escapeHtmlAttr($block->getContainerId()) ?>-container">
    </div>
</div>
<script>
    function initPayPalInContext<?= $escaper->escapeHtmlAttr($uniqueId) ?>() {
        return {
            clientConfig: <?= /** @noEscape */ $widgetJson ?>.clientConfig,
            customerSection: {},
            cartSection: false,
            isLoading: false,
            actions: {},
            alreadyLoaded: false,
            getData(data) {
                if (data.customer) {
                    this.customerSection = data.customer;
                }
                if (data.cart) {
                    this.cartSection = data.cart;
                    this.checkAndInitializeButtons()
                }
            },
            initializePayPalScript() {
                if (!window.paypalScriptPromise) {
                    window.paypalScriptPromise = new Promise((resolve, reject) => {
                        const scriptId = 'paypal-script';

                        let paypalScript = document.getElementById(scriptId);
                        if (paypalScript) {
                            if (window.paypal) {
                                resolve(window.paypal);
                            } else {
                                paypalScript.addEventListener('load', () => resolve(window.paypal), { once: true });
                                paypalScript.addEventListener('error', () => reject(new Error('PayPal SDK could not be loaded')), { once: true });
                            }
                            return;
                        }

                        const config = this.clientConfig;
                        const script = document.createElement('script');
                        script.src = config.sdkUrl;
                        script.id = scriptId;
                        script.setAttribute('data-partner-attribution-id', config.dataAttributes['data-partner-attribution-id']);

                        document.body.appendChild(script);

                        script.onload = () => resolve(window.paypal);
                        script.onerror = () => reject(new Error('PayPal SDK could not be loaded'));
                    });
                }

                return window.paypalScriptPromise;
            },
            async initializeButtons() {
                try {
                    await this.initializePayPalScript();
                    
                    const paypal = window.paypal;
                    const getCookie = this.getCookie;
                    const config = this.clientConfig;
                    const cartSection = this.cartSection;

                    paypal && paypal.Buttons({
                        style: {
                            ...config.styles,
                            height: 42, // Sets the style.height option to a value from 25 to 55.
                            disableMaxWidth: false, // The button has a default maximum width of 750px
                            tagline: false // Set the style.layout to horizontal for taglines.
                        },
                        onInit: (data, actions) => {
                            this.actions = actions || this.actions;
                        },
                        onClick(data, actions) {
                            this.isLoading = true;
                            
                            // Get form data
                            const form = document.getElementById('product_addtocart_form');
                            const formData = new FormData(form);
                            
                            let params = "";
                            for (let [key, value] of formData.entries()) {
                                if (params !== "") {
                                    params += "&";
                                }
                                params += `${key}=${encodeURIComponent(value)}`;
                            }
                            
                            const formKey = hyva.getFormKey();
                            
                            // Get product value and qty input element                            
                            const productValue = formData.get('product');
                            const qtyInput = document.getElementById('qty[' + productValue + ']');
                            
                            let postUrl;
                            let qtyValue;

                            const existingItemIndex = cartSection.items.findIndex(item => item.product_id === productValue);

                            if (existingItemIndex !== -1) {
                                const existingItem = cartSection.items[existingItemIndex];
                                postUrl = `${BASE_URL}checkout/cart/updateItemQty/`;
                                qtyValue = 5;
                            } else {
                                postUrl = `${BASE_URL}checkout/cart/add/`;
                                qtyValue = qtyInput && qtyInput.value ? parseInt(qtyInput.value, 10) : 1;
                            }

                            const paramsData = new URLSearchParams({
                                form_key: formKey,
                                product: productValue,
                                qty: qtyValue,
                                uenc: hyva.getUenc()
                            });
                            
                            return window.fetch(postUrl, {
                                "headers": {
                                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                                },
                                "body": paramsData.toString(),
                                "method": "POST",
                                "mode": "cors",
                                "credentials": "include"
                            })
                            .then(response => {                                
                                if (response.ok) {
                                    return response.json();
                                } else {
                                    window.dispatchMessages && window.dispatchMessages([{
                                        type: 'warning',
                                        text: '<?= $escaper->escapeJs(__('Could not update item from quote.')) ?>'
                                    }]);
                                    this.isLoading = false;
                                }
                            })    
                            .then(result => {
                                if (result.success) {
                                    window.dispatchMessages && window.dispatchMessages([{
                                        type: 'success',
                                        text: 'You updated the item.'
                                    }]);
                                } else {
                                    throw new Error(result.error_message || 'Unknown error occurred');
                                }
                            })
                            .catch(error => {
                                window.dispatchMessages && window.dispatchMessages([{
                                    type: 'error',
                                    text: error.message
                                }]);
                            })
                            .finally(() => {
                                this.isLoading = false;
                            });
                            
                        },
                        createOrder() {
                            const params = "quote_id=" + cartSection.cartId +
                                "&customer_id=" + (config.customerId ? config.customerId : '') +
                                "&form_key=" + (getCookie('form_key') || '') +
                                "&button=" + config.button;

                            return window.fetch(config.getTokenUrl, {
                                "headers": {
                                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                                },
                                "body": params,
                                "method": "POST",
                                "mode": "cors",
                                "credentials": "include"
                            })
                            .then(result => result.json())
                            .then(data => data.token)
                            .catch((error) => console.log(error));
                        },

                        onApprove(data, actions) {
                            const params = "paymentToken=" + (data.orderID || '') +
                                "&payerId=" + (data.payerID || '') +
                                "&quoteId=" + (cartSection.quoteId || '') +
                                "&customerId=" + (config.customerId || '') +
                                "&form_key=" + (getCookie('form_key') || '');

                            return window.fetch(config.onAuthorizeUrl, {
                                "headers": {
                                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                                },
                                "body": params,
                                "method": "POST",
                                "mode": "cors",
                                "credentials": "include"
                            })
                            .then(data => {
                                return data.json()
                            })
                            .then(response => {
                                if (response.success) {
                                    return actions.redirect(response.redirectUrl);
                                }

                                throw new Error(response['error_message']);
                            })
                            .catch((error) => console.log(error))
                            .finally(() => {
                                const reloadCustomerDataEvent = new CustomEvent("reload-customer-section-data");
                                window.dispatchEvent(reloadCustomerDataEvent);
                            });
                        },
                        onCancel(data, actions) {
                            // No changes as should remain on the same page
                        },
                        onError(err) {
                            // window.location.href = config.onCancelUrl;
                        }
                    }).render(this.$refs.paypalInContextProduct);
                } catch (error) {
                    console.error("Error loading PayPal SDK: ", error);
                }
            },
            checkAndInitializeButtons() {
                const form = document.getElementById('product_addtocart_form');
                if (!form) {
                    return;
                }
                if (this.cartSection && !this.alreadyLoaded) {
                    this.initializeButtons().then(() => {
                        this.alreadyLoaded = true;
                    });
                } else {
                    return;
                }
            },
            getCookie(name) {
                // Retrieves a cookie value by name
                const v = document.cookie.match('(^|;) ?' + name + '=([^;]*)(;|$)');
                return v ? v[2] : null;
            }
        }
    }
</script>
